name: neon_met_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'  # Daha net sürüm aralığı

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP & State
  dio: ^5.3.2
  provider: ^6.1.4

  # Routing
  auto_route: ^7.8.4

  # Animation
  lottie: ^2.6.0

  # Local Database
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1  # objectbox ile AYNI sürümde olmalı
  path_provider: ^2.1.5

  # JSON işlemleri
  json_annotation: ^4.8.1

  # Diğer
  curved_navigation_bar: ^1.0.6
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Kod üreticiler (VERSİYONLARI SABİTLEYİN!)
  build_runner: ^2.4.6  # "any" yerine spesifik sürüm
  auto_route_generator: ^7.3.0  # auto_route ile uyumlu
  json_serializable: ^6.7.1  # json_annotation ile uyumlu
  objectbox_generator: ^2.5.1  # objectbox ile AYNI sürüm
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/